### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by xabierr** [PatBall1/detectree2#125]
Hi there,
Trying to generate landscape predictions (as per tutoriaL) using the 230103_randresize_full.pth model. The tiling is working but when trying to predict I get the following error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-8-9fd5f839e851>](https://localhost:8080/#) in <cell line: 3>()
      1 trained_model = "/content/models/230103_randresize_full.pth"
      2 cfg = setup_cfg(update_model=trained_model)
----> 3 predict_on_data(tiles_path, predictor=DefaultPredictor(cfg))

7 frames
[/usr/local/lib/python3.10/dist-packages/torch/serialization.py](https://localhost:8080/#) in __init__(self, name_or_buffer)
    281 class _open_zipfile_reader(_opener):
    282     def __init__(self, name_or_buffer) -> None:
--> 283         super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
    284 
    285 

RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by PatBall1** [comment]
Hi @xabierr I see you closed this issue. Did you work out what the problem was?

**Comment by xabierr** [comment]
Yes. Used wget to get the prretrained model instead if uploading it directly

Sent on the go with Vodafone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
