### ISSUE TITLE
RuntimeWarning: invalid value encountered in cast

### ISSUE THREAD

**Issue by xabierr** [PatBall1/detectree2#137]
I am following the tutorial (generating landscape predictions) using Colab.

When running the following:

_Path to site folder and orthomosaic
site_path = "/content/drive/MyDrive/"
img_path = site_path + "Dan_2014_RGB_project_to_CHM.tif"
tiles_path = site_path + "/tilespred/"
 Read in the geotiff
data = rasterio.open(img_path)
 Location of trained model
model_path = "/content/drive/230103_randresize_full.pth"

Specify tiling
buffer = 30
tile_width = 40
tile_height = 40
tile_data(data, tiles_path, buffer, tile_width, tile_height, dtype_bool = True)_

I am getting the following warning:

**/usr/local/lib/python3.10/dist-packages/numpy/core/_asarray.py:126: RuntimeWarning: invalid value encountered in cast
  arr = array(a, dtype=dtype, order=order, copy=False, subok=subok)**

Anyone getting the same? Is it because of NoData values??

cheers,

Javier

**Comment by xabierr** [comment]
Hi Pat,

Running this on Colab (local runtime). 

For some reason, I cant load the whole file, so working with clipped rasters (clipped using ArcGIS Pro).

I get the error when exporting and leaving NoData empty (Clip_Dan_2014_RGB_project_NoData.tif). 

If I set a value for NoData (e.g. 65535... Clip_Dan_2014_RGB_project.tif), then I dont get the error.

In any case, resultant crowns with either file are not great. Link to images and code used here: https://www.dropbox.com/scl/fo/m6p524k2pvlic1b5ym89r/h?rlkey=flnowayyqkdo0dloiu7wcz16a&dl=0

Further question: what type of image does the model work with best? Does it have to be a 4-band 32 float as per example?

**Comment by PatBall1** [comment]
@xabierr looking at your clipped images, they are roughly 700 m x 400 m. Given the parameters, you should be tiling to 100 m x 100 m tiles, which would work fine. Have you checked to see how your tiled .png images look. If they are black I would refer you to the warning in the tutorial regarding the `tile_data_train` function:

`tile_data_train(data, out_dir, buffer, tile_width, tile_height, crowns, threshold)`

> [!Warning]
> If tiles are outputing as blank images set dtype_bool = True in the tile_data_train function. This is a bug and we are working on fixing it.

Regarding the image type, the models are designed to work with 3-band RGB images. When 4-band images are supplied, the fourth band is ignored (the fourth band of an RGB image typically give an alpha value which we ignore). We are currently working on an upgrade that will support multispectral images of 4 or more bands - this should be pushed to the repo in one month.

**Comment by xabierr** [comment]
Im setting "dtype_bool = True" but still getting blank images. If you use my code and images (https://www.dropbox.com/scl/fo/m6p524k2pvlic1b5ym89r/h?rlkey=flnowayyqkdo0dloiu7wcz16a&dl=0), do you get good results?

**Comment by PatBall1** [comment]
Hi @xabierr sorry it took me a while but I finally got round to checking your data. It works find without setting `dtype_bool = True`. So just use the default `tile_data(data, tiles_path, buffer, tile_width, tile_height)` and your tiles should come out fine! Let me know if you have any other issues.

**Comment by xabierr** [comment]
Thanks. That worked and my tiles are now working. However, crowns are still not looking great. This is my output: https://www.dropbox.com/scl/fi/6xs3f54836e45xayq4pve/crowns_clip.gpkg?rlkey=bxnmhsduu37xqa53f04qx12o3&dl=0

**Comment by PatBall1** [comment]
Great! Please be aware that there was a mistake in the tutorial previously. The last simplifying step should be:

```clean = clean.set_geometry(clean.simplify(0.3))```

and NOT:

```clean = clean.set_geometry(crowns.simplify(0.3))```
