### ISSUE TITLE
Process time for tilling? 

### ISSUE THREAD

**Issue by jldz9** [PatBall1/detectree2#143]
HI, just wondering what is the normal time range for tilling? 
I managed to get this run within a container, for the tilling part introduced in tutorial [part 2.4 ](https://patball1.github.io/detectree2/tutorial.html#generating-landscape-predictions) I have really bad performance.

The speed is average 1 tile per second for example data [Dan_2014_RGB_project_to_CHM.tif](https://zenodo.org/records/8136161/files/Dan_2014_RGB_project_to_CHM.tif?download=1) there are total of 12887 tiles which takes almost 4 hours to run. I'm not sure if it supposed to be this slow.  

My personal pc runs AMD 7840HS with 8 core 16 threads and  HPC with 48 core 96 threads both are really slow

**Comment by PatBall1** [comment]
Hi @jldz9 thanks for raising this. Tiling is not as optimised as it could be but it shouldn't quite be as slow are you describe. I haven't tried running within a container myself - is there a chance that it is limiting the resource allocation? Also, what parameters are you using as you tile? Having a small central area and large buffers can lead to a lot of duplication in the tiled output.

**Comment by jldz9** [comment]
Thanks for reply @PatBall1. I'm following the [tutorial](https://patball1.github.io/detectree2/tutorial.html#generating-landscape-predictions) and the tiling parameter is 
```
buffer = 30
tile_width = 40
tile_height = 40
```

**Comment by PatBall1** [comment]
@jldz9, if your systems are running slowly, try increasing the area of the tile and (with caution) decrease the buffer. Try, for example:
```buffer = 20
tile_width = 60
tile_height = 60 ```
This will reduce the number of tiles you need to make quite significantly, but things are likely to be a bit messier in the boundaries.

Alternatively, if you are just doing the tutorial to learn how to use the tool, why don't you crop the `Dan_2014_RGB_project_to_CHM.tif` raster to a smaller area before tiling?

If you have any suggestions for improving the tiling efficiency, please let me know!

**Comment by PatBall1** [comment]
@jldz9 Would you mind testing out the new tiling routine on the jb/july24 branch (`!pip install git+https://github.com/PatBall1/detectree2.git@jb/july24`)? I've implemented a parallelised routine and it seems to be working fine for me but I'd appreciate a second look before I merge with the main branch.

**Comment by jldz9** [comment]
> @jldz9 Would you mind testing out the new tiling routine on the jb/july24 branch (`!pip install git+https://github.com/PatBall1/detectree2.git@jb/july24`)? I've implemented a parallelised routine and it seems to be working fine for me but I'd appreciate a second look before I merge with the main branch. Existing scripts _should_ work the same.

Thanks for getting this done. I'll test this out sometime before this Friday.

**Comment by PatBall1** [comment]
The parallelised routine does speed things up a bit but it leads to dodgy outputs on the images and the shapes. Not sure why that is happening...

**Comment by jldz9** [comment]
> The parallelised routine does speed things up a bit but it leads to dodgy outputs on the images and the shapes. Not sure why that is happening...

One could be thread safety issue, I'm not the expert on multi-threading though..

**Comment by PatBall1** [comment]
@jldz9 I think you were right! I have implemented a new function that is much quicker and gives reliable results in my test. I've combined training and landscape prediction tiling into a single function `tile_data` - the behaviour changes depending on whether or not you supply training crowns.

**Comment by PatBall1** [comment]
I have merged changes into the main branch. They include the parallelised routine for tiling. It should run much quicker (if you are on a multi-core system).
