### ISSUE TITLE
Issue with Tiling Code in Tutorial Section 2.8 of detectree2: RuntimeWarning and AttributeError

### ISSUE THREAD

**Issue by chenyuanyuan12138** [PatBall1/detectree2#151]
hen running the tiling code provided in Section 2.8 of the detectree2 tutorial, I encountered several issues:
1.RuntimeWarning: While calling tile_data(), I repeatedly got the following warnings:
RuntimeWarning: overflow encountered in reduce
RuntimeWarning: invalid value encountered in cast
2.AttributeError: Additionally, during the tiling process, I encountered the following error:AttributeError: overlapping_crowns might be empty or invalid.

![微信图片_20241022093202](https://github.com/user-attachments/assets/42648d2c-7d87-4e4e-90c3-58d2ebb93f32)

**Comment by PatBall1** [comment]
@chenyuanyuan12138 I've recreated the error myself and will work on a fix now. The bug came from an update I made to the tiling function in the latest update.
