### ISSUE TITLE
pip install detectree2 

### ISSUE THREAD

**Issue by xixi-jodaHuang** [PatBall1/detectree2#73]
when I use pip install detectree2 ，it ERROR:

ERROR: Could not find a version that satisfies the requirement detectron2 (from detectree2) (from versions: none)
ERROR: No matching distribution found for detectron2

**Comment by PatBall1** [comment]
@xixi-jodaHuang detectree2 is yet to be uploaded to PyPI.
For now, please use `pip install git+https://github.com/PatBall1/detectree2.git`

**Comment by xixi-jodaHuang** [comment]
Thank you very much for your help. But I ran into another problem using your method this morning.

 Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
      ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In fact, I already have gdal installed."from osgeo import gdal" is ok. but "import gdal" failed

**Comment by PatBall1** [comment]
@xixi-jodaHuang thanks for your follow up.
GDAL does  tend to cause some issues. We have tried to cover them in our documentation here:
https://patball1.github.io/detectree2/contributing.html#gdal-complexities
Are you able to install it as suggested there?

**Comment by xixi-jodaHuang** [comment]
I'm sorry, I failed. I don't know if it's because I'm a win11 system.
[3.6.3. Building Detectree2 using Conda]This is my reference procedure.But I noticed in the file that the platform used was linux(environment.yaml)
'''
# Non-standard section listing target platforms for conda-lock:
# platforms:
#   - linux-64
'''
when i use "mamba env create -f envrironment.yaml", It always prompts:
EnvironmentFileNotFound: 'D:\detectree2\detectree2-matt-conda\detectree2-matt-conda\conda\envrironment.yaml' file not found
"d:\detectree2-matt-conda\detectree2-matt-conda\conda"  This is my path when I use the command.
Perhaps the biggest problem is that I'm using win system? Sorry, I am not a computer professional students, so may ask the question may be more basic.

**Comment by PatBall1** [comment]
@xixi-jodaHuang we have mostly been running things on linux environments and not tested on windows. I could recommend that you try Google Colab?

**Comment by xixi-jodaHuang** [comment]
Thanks, I'll try it later.
