### ISSUE TITLE
tutorial.html

### ISSUE THREAD

**Issue by Joda0515** [PatBall1/detectree2#77]
"If you would just like to make predictions on an orthomosaic with a pre-trained model from the model_garden, skip to part 4."

2.3 and 2.4 are missing from this document. When will they be updated?

Do I need to run this file now if I want to use the pre-trained model provided by the author for image prediction ?
>>>forest-modelling-detectree-v4.ipynb

Thanks again to the author's intention to answer, I wish you a happy life!

**Comment by PatBall1** [comment]
@xixi-jodaHuang I can update the tutorial shortly, but in the meantime, you can use the notebook that is in the package. See `detectree2/notebooks/colab/predictJB.ipynb`
This will take you through the process of making predictions.

**Comment by PatBall1** [comment]
I can supply you with a pre-trained model too. What kind of area are you predicting on?

**Comment by xixi-jodaHuang** [comment]
> 

Thank you very much!I look forward to your early update. I don't know if there is a pre-trained model for urban areas , if there is, it would be great.

**Comment by xixi-jodaHuang** [comment]
"!pip install git+https://github.com/PatBall1/detectree2.git@JB/refactor"
'''
 WARNING: Did not find branch or tag 'JB/refactor', assuming revision or ref.
  Running command git checkout -q JB/refactor
  error: pathspec 'JB/refactor' did not match any file(s) known to git.
WARNING: Discarding git+https://github.com/PatBall1/detectree2.git@JB/refactor. Command errored out with exit status 1: git checkout -q JB/refactor Check the logs for full command output.
ERROR: Command errored out with exit status 1: git checkout -q JB/refactor Check the logs for full command output.
'''
I encountered this problem while working with file(predictJB.ipynb).

**Comment by PatBall1** [comment]
@xixi-jodaHuang that file name should end with `.tif`. Does it work if you include that?

**Comment by xixi-jodaHuang** [comment]
img_path = site_path + "/Jodagiv.tif"
This is the path to my tif file.This part should be fine.

---------------------------------------------------------------------------

from detectree2.models.outputs import stitch_crowns, clean_crowns
folder = "/content/drive/MyDrive/detectree2/data/tilespred/predictions_geo"
crowns = stitch_crowns(folder,1)

---------------------------------------------------------------------------
After I manually added a "_" to the end of each "geojosn" file name, the code ran.

**Comment by Joda0515** [comment]
> 我认为问题出在平铺功能上——我忘记为新的文件格式更新它。我现在会调查一下。

Great. Keep me posted. Thank you.

**Comment by Joda0515** [comment]
> 我认为问题出在平稳运行上——我忘记了新的文件格式更新了它。我现在会调查一下。

Thank you very much and look forward to hearing from you.

**Comment by PatBall1** [comment]
@Joda0515 I think I have fixed the bug. Hopefully it will work now.
