### ISSUE TITLE
pytorch-lightning 1.8.1 requires PyYAML>=5.4, but you have pyyaml 5.1 which is incompatible.

### ISSUE THREAD

**Issue by Coder-GAN** [PatBall1/detectree2#79]
Hi there, I appreciate the gorgeous work built by the authors.
I faced an error that occurred when I used pip to install detectree2.

Environment: Ubuntu20.04 with Conda
Here is my code: pip install git+https://github.com/PatBall1/detectree2.git
ERROR: pytorch-lightning 1.8.1 requires PyYAML>=5.4, but you have pyyaml 5.1 which is incompatible.

Can somebody provide any suggestions? Thanks.

**Comment by Coder-GAN** [comment]
This error also happened on GoogleColab with pip install detectree2:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
notebook 5.7.16 requires jinja2<=3.0.0, but you have jinja2 3.1.2 which is incompatible.
dask 2022.2.0 requires pyyaml>=5.3.1, but you have pyyaml 5.1 which is incompatible.
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 Werkzeug-2.2.2 affine-2.3.1 antlr4-python3-runtime-4.9.3 arrow-1.2.3 black-22.3.0 click-8.1.3 click-plugins-1.1.1 cligj-0.7.2 detectree2-0.0.1 detectron2-0.6 fairscale-0.4.6 fiona-1.8.22 flask-2.2.2 fvcore-0.1.5.post20221122 geopandas-0.10.2 geos-0.2.3 huggingface-hub-0.11.0 hydra-core-1.2.0 iopath-0.1.9 itsdangerous-2.1.2 munch-2.5.0 mypy-extensions-0.4.3 omegaconf-2.2.3 pathspec-0.10.2 platformdirs-2.5.4 portalocker-2.6.0 proj-0.2.0 pycrs-1.0.2 pygeos-0.13 pypng-0.20220715.0 pyproj-3.2.1 pyyaml-5.1 rasterio-1.3a3 snuggs-1.4.7 timm-0.6.12 typed-ast-1.5.4 yacs-0.1.8
WARNING: The following packages were previously imported in this runtime:
  [pydevd_plugins]
You must restart the runtime in order to use newly installed versions.

**Comment by PatBall1** [comment]
@Coder-GAN - it's a bit messy but everything still works okay in Colab even with that error. We are still working on tidying up the platform compatibility / dependency issues.
