### ISSUE TITLE
Error downloading model_garden

### ISSUE THREAD

**Issue by rjstack266** [PatBall1/detectree2#80]
Following error on attempted install

Downloading model_garden/220723_withParacouUAV.pth (503 MB)
  Error downloading object: model_garden/220723_withParacouUAV.pth (b2fc7ff): Smudge error: Error downloading model_garden/220723_withParacouUAV.pth (b2fc7ff3006b429ddbae947ead4149efb74370df7a5686de0af8573b13f62537): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access

**Comment by PatBall1** [comment]
Hi @rjstack266 , thanks for raising this issue. We have indeed hit our LFS bandwidth limit. I will look into adding some more so that you can access the `model_garden` again!

**Comment by rjstack266** [comment]
Thank you! New to GIT/Python ecosystem - any easy way to get hold of a portion of the  package created and just install that?

**Comment by PatBall1** [comment]
@rjstack266 I added some extra bandwidth so it should work okay now
