### ISSUE TITLE
Rasterio 1.3a3 unable to build wheel

### ISSUE THREAD

**Issue by rjstack266** [PatBall1/detectree2#82]
I can install rasterio using conda install -c conda-forge rasterio.

The setup file does not recognize it as being installed and attempts to use rasterio 1.3a3 and cannot build the associated wheel.

Running windows using pip install git+url instructions 

Collecting rasterio==1.3a3
  Using cached rasterio-1.3a3.tar.gz (401 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
      ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by rjstack266** [comment]
Solved by forking and editing setup.py file

**Comment by PatBall1** [comment]
@rjstack266 thanks for sharing your experience. There are still some compatibility issues, especially with GDAL and Rasterio. We have not tested the system on Windows at all so, if possible, we would recommend using a Linux system. Google Colab is the platform on which most testing has been performed.
